apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cascade.fullname" . }}-api-gateway-config
  labels:
    {{- include "cascade.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ tpl (.Files.Get "files/nginx.conf") . | indent 4 }}
