apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cascade.fullname" . }}-board-query
  labels:
    {{- include "cascade.labels" . | nindent 4 }}
    app.kubernetes.io/component: board-query
spec:
  replicas: {{ .Values.boardQuery.replicaCount }}
  selector:
    matchLabels:
      {{- include "cascade.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: board-query
  template:
    metadata:
      labels:
        {{- include "cascade.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: board-query
    spec:
      containers:
        - name: board-query
          image: "{{ .Values.app.image.repository }}/board-query-service:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          env:
            - name: PORT
              value: "3003"
            - name: MONGODB_URI
              value: "mongodb://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb-headless:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb-headless:27017,{{ .Release.Name }}-mongodb-2.{{ .Release.Name }}-mongodb-headless:27017/cascade-board?replicaSet=rs0"
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
            - name: KAFKA_BROKERS
              value: "cascade-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cascade.fullname" . }}-secrets
                  key: JWT_SECRET
          resources:
            {{- toYaml .Values.boardQuery.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cascade.fullname" . }}-board-query
  labels:
    {{- include "cascade.labels" . | nindent 4 }}
    app.kubernetes.io/component: board-query
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cascade.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: board-query
