{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cascade.fullname" . }}-ingress
  labels:
    {{- include "cascade.labels" . | nindent 4 }}
  annotations:

    {{- if .Values.frontend.ingress.annotations }}
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - {{ if and .host (ne .host "*") }}host: {{ .host | quote }}{{ end }}
      http:
        paths:
          # API Gateway Route
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cascade.fullname" $ }}-api-gateway
                port:
                  number: 80
          # Frontend Route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cascade.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
