apiVersion: v2
name: cascade
description: A Helm chart for the Cascade microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Messaging
  - name: strimzi-kafka-operator
    version: 0.49.1
    repository: https://strimzi.io/charts/
  
  - name: kafka-ui
    version: 0.7.5
    repository: https://provectus.github.io/kafka-ui-charts
    condition: kafka-ui.enabled

  # Persistence
  - name: mongodb
    version: 18.1.20
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
    
  - name: redis
    version: 24.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
